### ISSUE TITLE
Submitting 2 questions

### ISSUE THREAD

**Issue by rijpkemadaan** [datacentricdesign/crowdsourced-quiz#1]
Hey Jacky,
I wasn't able to submit more than 1 question to the IO1075 Pool. When I tried to hand in two questions as usual the submit question did not respond. 
I tried to find the bug in the code for the page at the github page to try if I was able to solve it (due to this weeks "Software Development" module ofcours :)) but I couldn't find it. So I just report the issue here and hope we can fix it!
The button can be found at this page: https://io1075.io.tudelft.nl/submit_questions?module=7

**Comment by jackybourgeois** [comment]
Thanks for reporting @rijpkemadaan! I'll have a look this afternoon.

**Comment by jackybourgeois** [comment]
Thanks @rijpkemadaan I pushed the following commit to fix it: dd40356c8b362bda6855c6040759269249d97516
The addition of the if condition made the variable answerA2, answerB2... only available in the if condition, leading to an undefined error a few lines below.
